<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

</head>
<body>
  <ul>
            <li><a href="index.aspx">Home</a></li>
			<li><a href="#">My Account</a></li> 			           
            <li><a href="#">Change Password</a></li>
			<li><a href="subscribe.aspx">Subscribe</a></li>			
			<li><a href="logout.aspx">Logout</a></li>
        </ul>  
   
</body>
</html>
