<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

</head>
<body>
  <ul>
            <li><a href="LoginPage.aspx">Home</a></li>
			<li><a href="About.aspx">About Us</a></li> 			           
            <li><a href="Contact.aspx">Contact Us</a></li>
			<li><a href="Help.aspx">Help?</a></li>	
			
        </ul>  
   
</body>
</html>
